app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name='tienda'

urlpatterns = [
    # paths menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    
    
    
    

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths de autenticacion
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

gerudoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <title>Falcon Store</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'app/Scripts/estilo.css' %}" >
    <link rel="stylesheet" href="{% static 'app/Scripts/styles.css' %}" >
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

    
    <!-- jQuery library -->
    <script src="{% static 'app/Scripts/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'app/Scripts/alerta.js' %}"></script>
    <script src="{% static 'app/Scripts/utilidades.js' %}"></script>
    <script src="{% static 'app/Scripts/script.js' %}"></script>
    <script src="{% static 'app/Scripts/style.js' %}"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>

<body>
    <!-- Navigation-->
    
        

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <!-- <a class="navbar-brand" href="/">Jaguarete Kaa</a> -->
                <a class="navbar-brand" href="/">
                    <img src="{% static 'app/img/Logo/falcon4.png' %}" alt="" width="90" height="84">
                  </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                       
                        
                        <div class="dropdown show">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categorias
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            {% for categoria in categorias %}
                            <a class="dropdown-item" href="{% url 'tienda:productocategoria' categoria.id %}">{{categoria.nombre}}</a> {% endfor %}
                        </div>
                    </div>

                        
    
                        {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/listarproductos">
                                    Listado Productos
                                </a>
                        </li>
    
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/categorias">
                                    Listado Categorias
                                </a>
                        </li>
    
                        {% endif %}
    
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                Nosotros
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                Contacto
                            </a>
                        </li>
                    </ul>
                    <form class="d-flex d-md-inlne-block form-inline justify-content-end mt-3" method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-1 small text-left" name="buscador" placeholder="Buscar..." value="{{ request.POST.buscador }}">
                            &nbsp;
                            <div class="input-group-append">
                                <button class="btn btn-outline-info my-2 my-sm-0" type="submit"><i class="bi bi-search mr-sm-2"></i>Buscar</button>
                               
                            </div>
                        </div>
                    </form>


                    
                    <ul class="navbar-nav d-flex ml-auto mb-2 mb-lg-0 ms-lg-4">
                        {% if user.is_authenticated %}
                        <!-- Si está autenticado mostrar -->
                        {% load humanize %}
                        
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                <b>Hola! @{{ user.username }}</b>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">
                                        Cerrar Sesión
                                </a>
                        </li>
                        <div class="d-flex">
                            <a href="{% url 'tienda:viewcart' %}" class="btn btn-outline-primary">
                                <i class="fa fa-shopping-cart me-1"></i>
                                <span class="badge bg-primary text-black ms-1 rounded-pill">$ {{ importe_total_carro | intcomma }}</span>
                            </a>
                        </div>
                        {% else %}
                        <!-- Si no está autenticado mostrar -->
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/login">
                                Ingresar
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/registrar">
                                Registrar
                            </a>
                        </li>
                        
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
                    
                                                        
        
            

        
        

       

            
    

{% if messages %}
         {% for m in messages %}
            {{m}}
        {% endfor %}
{% endif %}



    {% block content %}

    
    {% endblock content %}




    <footer class="bg-light text-black pt-5 pb-4">

        <div class="container text-center text-md-left">
    
            <div class="row text-center text-md-left">
    
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Company Name</h5>
                    <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
              ital consectetur lorem ipsum dolor sit amet adipisicing elit.</p>
                    
                </div>
    
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Products</h5>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;"> TheProviders</a>
                </p>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;"> Creativity</a>
                </p>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;"> SourceFiles</a>
                </p>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;"> bootstrap 5 alpha</a>
                </p>
    
                </div>
    
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Useful links</h5>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;"> Your Account</a>
                </p>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;"> Become an Affiliates</a>
                </p>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;">Shipping Rates</a>
                </p>
                <p>
                    <a href="#" class="text-black" style="text-decoration: none;"> Help</a>
                </p>
                </div>
    
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning" >Contact</h5>
                    <p>
                        <i class="fas fa-home mr-3"></i>New York, NY 2333, US
                    </p>
                    <p>
                        <i class="fas fa-envelope mr-3"></i>theproviders98@gmail.com
                    </p>
                    <p>
                        <i class="fas fa-phone mr-3"></i>+92 3162859445
                    </p>
                    <p>
                        <i class="fas fa-print	 mr-3"></i>+01 335 633 77
                    </p>
                </div>
                
            </div>
    
            <hr class="mb-4">
    
            <div class="row align-items-center">
    
                <div class="col-md-7 col-lg-8">
                    <p>	Copyright ©2020 All rights reserved by:
                        <a href="#" style="text-decoration: none;">
                            <strong class="text-warning">The Providers</strong>
                        </a></p>
                    
                </div>
    
                <div class="col-md-5 col-lg-4">
                    <div class="text-center text-md-right">
    
                        <ul class="list-unstyled list-inline">
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm text-black" style="font-size: 23px;"><i class="fab fa-facebook"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm text-black" style="font-size: 23px;"><i class="fab fa-twitter"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm text-black" style="font-size: 23px;"><i class="fab fa-google-plus"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm text-black" style="font-size: 23px;"><i class="fab fa-linkedin-in"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm text-black" style="font-size: 23px;"><i class="fab fa-youtube"></i></a>
                            </li>
                        </ul>
                        
                    </div>
                    
                </div>
                
            </div>
    
        </div>
        
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- MESSAGES-->
    {% if messages %} {% for message in messages %}
    <script>
        Swal.fire({
            "title": "Felicitaciones!!",
            "text": "{{ message }}",
            "icon": "success"
        })
    </script>
    {% endfor %} {% endif %}
    <!-- END MESSAGES -->
</body>

</html>