app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name='tienda'

urlpatterns = [
    # paths menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    
    
    
    

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths de autenticacion
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

gerudoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/carrito/cart.html
{% extends 'layouts/base.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-9 col-md-8 col-sm-6 mx-auto ">

                <div class="card">
                    <div class="card-header text-center">
                        <strong>CARRITO</strong>
                    </div>
                    <div class="card body p-2">
                        {% load humanize %}
                        <h4>Total: <strong> 
                            $ {{ importe_total_carro | intcomma }}
                        </strong></h4>
                        <h4>Total Productos: <strong> 
                             {{ total_carro}}
                        </strong></h4>

                    </div>

                    <div class="card-element table-responsive">
                        <table class="table table-condensed">
                            <thead class="text-center">
                                <tr>
                                    <th>Item</th>
                                    <th colspan="3">Cantidad</th>
                                    <th>Subtotal</th>
                                    <th>Eliminar</th>
                                </tr>
                            </thead>
                            <tbody class="py-4">
                                {% if request.session.carro.items %} {% for key, value in request.session.carro.items %}
                                <tr>
                                    <td>{{ value.nombre }}</td>

                                    {% load bootstrap_icons %}
                                    <td class="text-center" colspan="3">
                                        {{ value.cantidad }}
                                        <a href="{% url 'tienda:addcart' value.producto_id %}" class="btn btn-secondary btn-sm" type="button"><i>{% bs_icon 'plus' %}</i></a>

                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:restarcart' value.producto_id %}" type="button"><i>{% bs_icon 'dash' %}</i> </a>
                                    </td>
                                    {% load humanize %}
                                    <td class="text-center">${{ value.precio | intcomma }} </td>
                                    <td class="text-center">
                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:delcart' value.producto_id %}" type="button"><i>{% bs_icon 'trash' %}</i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <tr>
                                    <td colspan="5">
                                        <div class="alert alert-danger text-center ">

                                            No se agregaron productos al carrito

                                        </div>
                                </tr>
                                </tr>
                                {% endif %}

                            </tbody>
                        </table>

                    </div>

                    
                </div>
                <div class=" text-center mt-3 mx-auto ">
                    {% if request.session.carro.items %}
                    <a class="btn btn-danger mx-auto mt-0 " href="{% url 'tienda:procesar_compra' %}">Procesar Compra</a> {% else %}
                    <a class="btn btn-danger mx-auto mt-0 disabled" href="">Procesar Compra</a> {% endif %}
                </div>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-3 my-4 mx-auto ">
                <div class="card card-footer align-item-center ">
                    <a href="/ " class="btn btn-dark my-2 mx-auto ">Volver a Tienda</a>
                    <a href="{% url 'tienda:cleancart' %}" class="btn btn-dark my-2 mx-auto ">Limpiar Carrito</a>
                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}