app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name='tienda'

urlpatterns = [
    # paths menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    
    
    
    

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths de autenticacion
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

gerudoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/categorias.html
{% extends 'layouts/base.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body  table-responsive">
                        <div class="d-flex justify-content-end mb-2 mx-2">
                            <a href="/addcategoria" class="btn btn-dark btn-sm pull-right" type="submit">
                            Nueva Categoria
                            </a>
                        </div>
                        <table class="table table-condensed">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% load bootstrap_icons %} {% if entity %} {% for categoria in entity %}
                                <tr>
                                    <td>{{ categoria.id }}</td>
                                    <td>{{ categoria.nombre }}</td>
                                    <td colspan="2" class="text-center">
                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:editcategoria' categoria.id %}" type="button"><i class="fa fa-pencil"></i></a>
                                        <a class="btn btn-danger btn-sm" href="{% url 'tienda:deleteCategoria' categoria.id %}" type="button"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No existen Productos relacionados a esta categoria</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                        <div>
                            {% include 'paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/devoluciones.html
{% extends 'layouts/base.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">DEVOLUCIONES</h3>
        <div class="row py-auto">
            <div class="col-10 mx-auto animate__animated animate__backInRight animate__delay-0.3s ">
                <p class="text-justify">
                    Si el producto entregado al Cliente fuese diferente al solicitado, el mismo Cliente podrá desistir de la compra, y JAGUARETE KAA S.A. procederá a la devolución de valor abonado por este. El Cliente dispone de 5 dias hábiles posterior a la entrega para
                    realizar el reclamo correspondiente. </p>
                <p class="text-justify">El orden de reembolso se realizará dentro de las 48 horas hábiles siguientes al reclamo del Cliente, y se hará efectiva a la cuenta de este según las políticas de las operadoras de tarjetas de crédito.
                </p>
                <p class="text-justify">
                    <span class="font-weight-bold"> Observación:</span> En ningún caso se prodrá proceder a realizar reembolso por un medio diferente al empleado para el pago. En todos los casos se deberá conservar la factura de compra.
                </p>
                <div class="col-10 text-right">
                    <a href="/" class="btn btn-dark my-4 mx-auto">Atras</a>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends "layouts/base.html" %} {% load static %} {% block content %}
<div class="min-vh-100 d-flex flex-colum pb-3">
    <div class="container">

        <!-- Header-->
        <div class="container-fluid mt-3">
            <div id="demo" class="carousel slide" data-ride="carousel">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                    <li data-target="#demo" data-slide-to="3"></li>
                </ul>

                <!-- The slideshow -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <a href="#">
                            <img  srcset="{% static 'app/img/spdigitaltest/Desktop1.png' %} 2000w, {% static 'app/img/spdigitaltest/Mobile1.png' %} 1000w" alt="Gabinete" width="100%" height="100%">
                        </a>
                    </div>
                    <div class="carousel-item">
                        <a href="#">
                            <img srcset="{% static 'app/img/spdigitaltest/Desktop2.png' %} 2000w, {% static 'app/img/spdigitaltest/Mobile2.png' %} 1000w" alt="Fuente_de_poder" width="100%" height="100%">
                        </a>
                    </div>
                    <div class="carousel-item">
                        <a href="#">
                            <img srcset="{% static 'app/img/spdigitaltest/Desktop3.png' %} 2000w, {% static 'app/img/spdigitaltest/Mobile3.png' %} 1000w" alt="" width="100%" height="100%">
                        </a>
                    </div>
                    <div class="carousel-item">
                        <a href="#">
                            <img srcset="{% static 'app/img/spdigitaltest/Desktop4.png' %} 2000w, {% static 'app/img/spdigitaltest/Mobile4.png' %} 1000w" alt="" width="100%" height="100%">
                        </a>
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
        </div>

        

        <form class="d-flex d-md-inlne-block form-inline justify-content-end mt-3" method="POST" action="">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" class="form-control bg-light border-1 small text-left" name="buscador" placeholder="Buscar..." value="{{ request.POST.buscador }}">
                &nbsp;
                <div class="input-group-append">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit"><i class="bi bi-search mr-sm-2"></i>Buscar</button>
                   
                </div>
            </div>
        </form>

        
        

        <section class="py-2">
            <div class="container px-4 px-lg-1 mt-2">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if entity %} {% for producto in entity %}
                    <div class="col my-3">
                        <div class="card h-100 text-center py-3">
                            <!-- Product image-->
                            {% if producto.imagen %}
                            <img class="mx-auto d-block img-fluid" src="{{ producto.imagen.url }}" alt="producto" width="150px%" /> {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="sinImagen" /> {% endif %}
                            <!-- Product details-->
                            {% load humanize %}
                            <div class="card-body p-3">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                    <!-- Product price-->
                                    $ {{ producto.precio | intcomma }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-2 pt-2 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-dark mt-auto" href="{% url 'tienda:detalleproducto' producto.id %}">Ver detalle</a> 
                                    {% if user.is_authenticated%}
                                    <a href="{% url 'tienda:addcart' producto.id %}" class="btn btn-primary mt-2" type="button">
                                        <i class="bi-cart-fill me-1"></i> Agregar al Carrito
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %} {% else %}
                    <div class="text-center text-warning">
                        <h3> No se encontraron Productos!!</h3>
                    </div>
                    {% endif %}
                </div>

                <div>
                    {% include 'paginator.html' %}
                </div>
            </div>

        </section>
    </div>
</div>
{% endblock %}

app/templates/paginator.html
{% if paginator.num_pages > 1 %}
    
    <div class="d-flex justify-content-center">
        <ul class="pagination">
            {% if entity.has_previous %}
                <li class="page-item d-none d-sm-block">
                    <a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a>
                </li>
            {% endif %} 

            {% for page in paginator.page_range %} 
                {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                    {% if entity.next_page_number != paginator.num_pages%}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                        </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ paginator.num_pages }}#pagtable">
                            {{paginator.num_pages}}
                        </a>
                    </li>
                {% endif %} 

                {% if page == entity.number and page > 7 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
                    </li>
                {% endif %} 

                {% if page < 7 or page == entity.number %} 
                    <li class="page-item {% if page == entity.number %} active{% endif %}">
                        <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
                    </li>
                {% endif %} 
            {% endfor %} 

            {% if entity.has_next %}
                <li class="page-item d-none d-sm-block">
                    <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
                </li>
            {% endif %}
        </ul>
    </div>

    <div class="d-flex justify-content-center d-sm-none">
        {% if entity.has_previous %}
            <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span> 
        {% endif %} 

        {% if entity.has_next %}
            <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span> 
        {% endif %}
            <br>
            <br>
    </div>
    
{% endif %}